class Constants:
    ASSESSMENT_TABLE = "assessment"
    ASSESSMENT_LOGS = "assessmentlogs"
    SUT_TABLE = "sut"
    TEST_SUITE_TABLE = "TestSuite"
    FEATURE_TABLE = "feature"
    FEATURE_COLLECTION_TABLE = "featurecollection"
    SCENARIO_TABLE = "scenario"
    SCENARIO_LOGS_TABLE = "scenariologs"
    STEP_TABLE = "step"
    STEP_CONFIG_TABLE = "stepconfig"
    STEP_LOGS_TABLE = "steplogs"
    MOCK_AA_REQ_RES = "MockAAReqRes"
    MOCK_AA_REQ_RESPONSE_SLOGS = "MockAAReqResponsesLogs"
